### Obtener todos los Dj
GET http://localhost:3000/api/dj

### POST un Dj
# @name createDjClass
POST http://localhost:3000/api/dj
Content-Type: application/json

{
  "nombreArtistico": "Juancito",
  "estado": "Disponible",
  "montoDj": 123,
  "foto": "algo.jpg",
  "solicitud": 1  // Añadido - ID de la solicitud existente
}

### Crear un nuevo Dj
# @name createDjClass2
POST http://localhost:3000/api/dj
Content-Type: application/json

{
  "nombreArtistico": "Juan",
  "estado": "Ocupado",
  "montoDj": 1234,
  "foto": "algoo.jpg",
  "solicitud": 1  // Añadido - ID de la solicitud existente
}

### ID
@id = {{createDjClass.response.body.data.id}}

### Obtener un Dj por ID
GET http://localhost:3000/api/dj/{{id}}

### ID A BORRAR
@idToDelete = {{createDjClass2.response.body.data.id}}

### Actualizar un Dj existente
PUT http://localhost:3000/api/dj/{{id}}
Content-Type: application/json

{
  "nombreArtistico": "Juannnnn",
  "estado": "Ocupado",
  "montoDj": 1234
}

### Eliminar un Dj
DELETE http://localhost:3000/api/dj/{{idToDelete}}