### Obtener todos los Dj
GET http://localhost:3000/api/dj


### POST un Dj
# @name createDjClass

POST http://localhost:3000/api/dj
Content-Type: application/json

{
  "nombre": "Juancito",
  "apellido": "Pérez 2",
  "email": "juan.perez@ejedsadasmplo.com",
  "password": "contrasedsadsaña123",
  "telefono": "123432432456789",
  "nombreUsuario": "juanperez2"
}

### Crear un nuevo Dj
# @name createDjClass2

POST http://localhost:3000/api/dj
Content-Type: application/json

{
  "nombre": "Juan",
  "apellido": "Pérez",
  "email": "juan.perez@ejemplo.com",
  "password": "contraseña123",
  "telefono": "123456789",
  "nombreUsuario": "juanperez"
}

### ID
@id = {{createDjClass.response.body.data.id}}

### Obtener un Dj por ID

GET http://localhost:3000/api/dj/{{id}}


### ID A BORRAR
@idToDelete = {{createDjClass2.response.body.data.id}}

### Actualizar un Dj existente
PUT http://localhost:3000/api/dj/{{id}}
Content-Type: application/json

{
  "nombre": "Juan",
  "apellido": "Pérez Actualizado",
  "email": "juan.perez.actualizado@ejemplo.com"
}

### Eliminar un Dj
DELETE http://localhost:3000/api/dj/{{idToDelete}}