### Obtener todos los clientes
GET http://localhost:3000/api/cliente
Accept: application/json

### Obtener un cliente por ID
GET http://localhost:3000/api/cliente/1
Accept: application/json

### Crear un nuevo cliente
POST http://localhost:3000/api/cliente
Content-Type: application/json
Accept: application/json

{
  "nombre": "Juan",
  "apellido": "Pérez",
  "email": "juan.perez@ejemplo.com",
  "password": "contraseña123",
  "telefono": "123456789",
  "nombreUsuario": "juanperez"
}

### Crear un nuevo cliente
POST http://localhost:3000/api/cliente
Content-Type: application/json
Accept: application/json

{
  "nombre": "Juancito",
  "apellido": "Pérez 2",
  "email": "juan.perez@ejemplo.com",
  "password": "contraseña123",
  "telefono": "123456789",
  "nombreUsuario": "juanperez2"
}

### Actualizar un cliente existente
PUT http://localhost:3000/api/cliente/1
Content-Type: application/json
Accept: application/json

{
  "nombre": "Juan",
  "apellido": "Pérez Actualizado",
  "email": "juan.perez.actualizado@ejemplo.com"
}

### Eliminar un cliente
DELETE http://localhost:3000/api/cliente/1
Accept: application/json