### Obtener todos los clientes
GET http://localhost:3000/api/cliente


### POST un cliente
# @name createClienteClass

POST http://localhost:3000/api/cliente
Content-Type: application/json

{
  "nombre": "Juancito",
  "apellido": "Pérez 2",
  "email": "juan.perez@ejedsadasmplo.com",
  "password": "contrasedsadsaña123",
  "telefono": "123432432456789",
  "nombreUsuario": "juanperez2"
}

### Crear un nuevo cliente
# @name createClienteClass2

POST http://localhost:3000/api/cliente
Content-Type: application/json

{
  "nombre": "Juan",
  "apellido": "Pérez",
  "email": "juan.perez@ejemplo.com",
  "password": "Contraseña123",
  "telefono": "123456789",
  "nombreUsuario": "juanperez"
}

### ID
@id = {{createClienteClass2.response.body.data.id}}
### Obtener un cliente por ID
GET http://localhost:3000/api/cliente/{{id}}

### Obtener un cliente por email y password
POST http://localhost:3000/api/cliente/login
Content-Type: application/json

{
  "email": "juan.perez@ejemplo.com",
  "password": "Contraseña123"
}

### ID A BORRAR
@idToDelete = {{createClienteClass2.response.body.data.id}}

### Actualizar un cliente existente
PUT http://localhost:3000/api/cliente/{{id}}
Content-Type: application/json

{
  "nombre": "Juannnnn",
  "apellido": "Pérez Actualizado",
  "email": "juan.perez.actualizado@ejemplo.com"
}

### Eliminar un cliente
DELETE http://localhost:3000/api/cliente/{{idToDelete}}



###logout
POST http://localhost:3000/api/cliente/logout
Content-Type: application/json


### verify and get Profile
POST http://localhost:3000/api/cliente/verify
Content-Type: application/json