### Obtener todos las barras
GET http://localhost:3000/api/barra


### POST una barra
# @name createBarraClass

POST http://localhost:3000/api/barra
Content-Type: application/json

{
  "nombreB": "Barra B",
  "tipoBebida": "cerveza",
  "montoB": 1234,
  "foto": "algoo.jpg"
}

### POST una barra
# @name createBarraClass2

POST http://localhost:3000/api/barra
Content-Type: application/json

{
  "nombreB": "Barraaaa B",
  "tipoBebida": "cervezaa",
  "montoB": 12345,
  "foto": "algooo.jpg"
}

### ID
@id = {{createBarraClass.response.body.data.id}}

### Obtener una barra por ID

GET http://localhost:3000/api/barra/{{id}}

### Actualizar una barra existente
PUT http://localhost:3000/api/barra/{{id}}
Content-Type: application/json

{
  "nombreB": "Barra actualizada",
  "tipoBebida": "cerveza",
  "montoB": 1234,
  "foto": "algoo.jpg"
}

### Eliminar una barra
DELETE http://localhost:3000/api/barra/{{id}}