### Obtener todos las barras
GET http://localhost:3000/api/barra


### POST una barra
# @name createBarraClass

POST http://localhost:3000/api/barra
Content-Type: application/json

{

}

### Crear una nuevo barra
# @name createBarraClass2

POST http://localhost:3000/api/barra
Content-Type: application/json

{

}

### ID
@id = {{createBarraClass.response.body.data.id}}

### Obtener una barra por ID

GET http://localhost:3000/api/barra/{{id}}


### ID A BORRAR
@idToDelete = {{createBarraClass2.response.body.data.id}}

### Actualizar una barra existente
PUT http://localhost:3000/api/barra/{{id}}
Content-Type: application/json

{

}

### Eliminar una barra
DELETE http://localhost:3000/api/barra/{{idToDelete}}