###GET ALL

GET http://localhost:3000/api/solicitud


###POST - Solicitud completa (todos los servicios)
# @name createSolicitudClass

POST http://localhost:3000/api/solicitud
Content-Type: application/json

{
    "usuario": 1,
    "dj": 1,
    "salon": 1,
    "gastronomico": 1,
    "barra": 1,
    "fechaSolicitud": "21/05/2025",
    "estado": "activa"
}

###POST - Solicitud solo con DJ y Salon
# @name createSolicitudPartial1

POST http://localhost:3000/api/solicitud
Content-Type: application/json

{
    "usuario": 1,
    "dj": 1,
    "salon": 1,
    "fechaSolicitud": "22/05/2025",
    "estado": "pendiente"
}

###POST - Solicitud solo con Gastronomico
# @name createSolicitudPartial2

POST http://localhost:3000/api/solicitud
Content-Type: application/json

{
    "usuario": 1,
    "gastronomico": 1,
    "fechaSolicitud": "23/05/2025",
    "estado": "pendiente"
}

###ID
@id = {{createSolicitudClass.response.body.data.id}}

### GET ONE
GET http://localhost:3000/api/solicitud/{{id}}

### PUT

PUT http://localhost:3000/api/solicitud/{{id}}
Content-Type: application/json

{
    "estado": "cancelada"
}

###DELETE

DELETE http://localhost:3000/api/solicitud/{{id}}